sudo: required
dist: bionic
languague: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd REST-with-ASP-NET/
  - echo "I am in the right folder!"
 script:
  - docker-compose build
 before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider:script
  script: docker push "$DOCKER_USERNAME"/rest-with-asp-net-udemy-db
    docker tag rest-with-asp-net:latest "$DOCKER_USERNAME"/r"$DOCKER_USERNAME"est-with-asp-net:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net-udemy-db:latest "$DOCKER_USERNAME"/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
    docker push "$DOCKER_USERNAME"/rest-with-asp-net:$TRAVIS_JOB_ID;
    docker push "$DOCKER_USERNAME"/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
  on:                                                        
    branch: master
notifications:
  email: false
    